services:
  postgres:
    image: postgres:15
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dragonhack
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      # - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - app-network

  pejmo-backend:
    image: tcerne/pejmo-backend:latest
    container_name: pejmo-backend
    #env_file:
    #  - .env
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - postgres

volumes:
  postgres-db-volume:

networks:
  app-network:

